const QUESTIONS=[...(window.Q1||[]),...(window.Q2||[]),...(window.Q3||[]),...(window.Q4||[])],KEY='yazeed-roadmap-a2-v3';
let state=JSON.parse(localStorage.getItem(KEY)||'{"results":{}}'),view='home',qUnit=1,qPos=0,order=[];
const norm=s=>String(s??'').toLowerCase().replace(/[’‘`]/g,"'").replace(/[–—]/g,'-').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ').replace(/\s*,\s*/g,',').trim();
const qkey=q=>`${q.unit}-${q.exercise}-${q.n}`, done=u=>QUESTIONS.filter(q=>q.unit===u&&state.results[qkey(q)]).length, correct=u=>QUESTIONS.filter(q=>q.unit===u&&state.results[qkey(q)]?.ok).length;
function save(){localStorage.setItem(KEY,JSON.stringify(state));document.getElementById('overall').textContent=Object.keys(state.results).length+'/120'}function setTab(v){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.v===v))}
function home(){return `<section class="card hero"><div><span class="pill">ROADMAP A2 · Units 1–4</span><h2>مذاكرة منظمة قبل الاختبار</h2><p class="muted">الشرح يغطي 1A إلى 4D. لكل وحدة اختبار 30 بندًا من <b>Check and reflect</b> بالنص نفسه الموجود في الكتاب، مع رقم الصفحة والتمرين والسؤال.</p><div class="note"><b>الاستخدام:</b> راجع الدرس، تعرّف نمط السؤال، ثم اختبر نفسك. البدائل تُكتب بالترتيب، والمطابقة بالحرف، والفراغ بالكلمة المطلوبة.</div></div><img src="icon.svg" alt="Roadmap A2"></section><div class="grid">${UNITS.map(u=>`<article class="card unitcard"><span class="pill">Pages ${u.pages}</span><h3>Unit ${u.id} — ${u.title}</h3><p class="muted">4 دروس + 30 سؤالًا حرفيًا من صفحة ${u.check}.</p><div class="progress"><div style="width:${done(u.id)/30*100}%"></div></div><p class="mini">تمت الإجابة: ${done(u.id)}/30 · الصحيح: ${correct(u.id)}</p><button class="btn" onclick="openUnit(${u.id})">شرح الوحدة</button> <button class="btn secondary" onclick="startQuiz(${u.id})">ابدأ الاختبار</button></article>`).join('')}</div>`}
function unitPage(id){const u=UNITS.find(x=>x.id===id);return `<section class="card"><div class="quizhead"><div><span class="pill">Pages ${u.pages}</span><h2>Unit ${u.id} — ${u.title}</h2></div><button class="btn" onclick="startQuiz(${id})">اختبار 30 سؤالًا</button></div><p class="muted">ركّز على شكل السؤال: اختيار بديل، إكمال فراغ، مطابقة، تصحيح خطأ، أو تكوين سؤال.</p></section><div class="grid">${u.lessons.map(l=>`<article class="card lesson"><span class="pill">${l.code} · p.${l.pages}</span><h3>${l.title}</h3><h4>Grammar / Function</h4><div class="english">${l.grammar}</div><h4>Vocabulary</h4><div class="english">${l.vocab}</div><h4>طرق الأسئلة والنقاط التي تُختبر</h4><ul class="tips">${l.tips.map(t=>`<li class="english">${t}</li>`).join('')}</ul></article>`).join('')}</div>`}
function quizLanding(){return `<section class="card"><h2>اختبارات الكتاب الحرفية</h2><p class="muted">كل وحدة = 30 بندًا حرفيًا من صفحة Check and reflect الخاصة بها، مع المرجع الدقيق.</p><div class="grid">${UNITS.map(u=>`<article class="card"><h3>Unit ${u.id}</h3><p>Page ${u.check} · 30 questions</p><p>الصحيح: <b>${correct(u.id)}</b> من <b>${done(u.id)}</b></p><button class="btn" onclick="startQuiz(${u.id})">ابدأ</button></article>`).join('')}</div><button class="btn gold" onclick="resetAll()">مسح كل النتائج</button></section>`}
function startQuiz(u){qUnit=u;qPos=0;order=QUESTIONS.filter(q=>q.unit===u);view='quiz';setTab('quiz');render();scrollTo(0,0)}
function quiz(){if(!order.length)return quizLanding();const q=order[qPos],r=state.results[qkey(q)];return `<section class="card"><div class="quizhead"><div><span class="pill">Unit ${qUnit}</span><h2>السؤال ${qPos+1} من 30</h2></div><div><b>${correct(qUnit)}</b> صحيح / <b>${done(qUnit)}</b> مجاب</div></div><div class="progress"><div style="width:${(qPos+1)/30*100}%"></div></div><div class="toc" style="margin-top:12px">${order.map((x,i)=>`<button class="qnum ${state.results[qkey(x)]?'done':''} ${i===qPos?'current':''}" onclick="jump(${i})">${i+1}</button>`).join('')}</div></section><section class="card"><div class="source">${q.source}</div><div class="help">${q.help||''}</div>${q.context?`<div class="context">${q.context}</div>`:''}<div class="qtext">${q.text}</div><div class="answerrow"><input id="ans" autocomplete="off" placeholder="Type your answer here" value="${r?String(r.value).replace(/"/g,'&quot;'):''}" ${r?'disabled':''}><button class="btn" onclick="check()" ${r?'disabled':''}>تحقق</button></div><div id="fb" class="feedback ${r?(r.ok?'ok':'bad'):''}">${r?(r.ok?'✓ Correct':'✗ Incorrect') : ''}${r?`<div class="key">Answer: ${q.answer}</div>`:''}</div><div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><button class="btn secondary" onclick="prev()" ${qPos===0?'disabled':''}>السابق</button><button class="btn secondary" onclick="reveal()">عرض الإجابة</button><button class="btn" onclick="next()">${qPos===29?'النتيجة':'التالي'}</button></div></section>`}
function check(){const q=order[qPos],el=document.getElementById('ans'),n=norm(el.value),ok=q.accept.some(a=>norm(a)===n);state.results[qkey(q)]={value:el.value,ok};save();render()}function reveal(){const q=order[qPos],fb=document.getElementById('fb');fb.className='feedback bad';fb.innerHTML=`<div>الإجابة الصحيحة:</div><div class="key">${q.answer}</div>`}function prev(){if(qPos>0){qPos--;render();scrollTo(0,0)}}function next(){if(qPos<29){qPos++;render();scrollTo(0,0)}else finish()}function jump(i){qPos=i;render();scrollTo(0,0)}
function finish(){const c=correct(qUnit);document.getElementById('app').innerHTML=`<section class="card"><span class="pill">Unit ${qUnit}</span><h2>النتيجة: ${c}/30</h2><p class="muted">${c>=27?'ممتاز جدًا. راجع البنود التي أخطأت فيها فقط.':c>=24?'جيد جدًا؛ أعد الأسئلة الخاطئة.':c>=18?'تحتاج مراجعة القواعد قبل الإعادة.':'ارجع لشرح الوحدة ثم أعد الاختبار كاملًا.'}</p><button class="btn" onclick="startQuiz(${qUnit})">إعادة الاختبار</button> <button class="btn secondary" onclick="openUnit(${qUnit})">مراجعة الشرح</button></section>`;order=[]}
function resetAll(){if(confirm('هل تريد مسح جميع النتائج؟')){state={results:{}};save();render()}}function openUnit(id){view='u'+id;setTab(view);render();scrollTo(0,0)}function render(){const app=document.getElementById('app');if(view==='home')app.innerHTML=home();else if(view.startsWith('u'))app.innerHTML=unitPage(Number(view.slice(1)));else app.innerHTML=quiz();save()}
document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;view=b.dataset.v;if(view!=='quiz')order=[];setTab(view);render();scrollTo(0,0)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
